/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XDSLIdeModule extends AbstractXDSLIdeModule {
}
