/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.scoping;

import com.mesev.dsl.xDSL.AssembledWorkflow;
import com.mesev.dsl.xDSL.CompositeWorkflow;
import com.mesev.dsl.xDSL.ExperimentTaskConfiguraiton;
import com.mesev.dsl.xDSL.Space;
import com.mesev.dsl.xDSL.TaskConfiguration;
import com.mesev.dsl.xDSL.Workflow;
import com.mesev.dsl.xDSL.XDSLPackage;
import java.util.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XDSLScopeProvider extends AbstractXDSLScopeProvider {
  public CompositeWorkflow getParentWorkflow(final Workflow workflow) {
    if ((workflow instanceof CompositeWorkflow)) {
      return ((CompositeWorkflow)workflow);
    }
    Workflow wf = workflow;
    while ((wf instanceof AssembledWorkflow)) {
      wf = ((AssembledWorkflow) wf).getParent();
    }
    if ((wf instanceof CompositeWorkflow)) {
      return ((CompositeWorkflow)wf);
    } else {
      return null;
    }
  }

  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    if ((context instanceof TaskConfiguration)) {
      boolean _equals = Objects.equals(reference, XDSLPackage.Literals.TASK_CONFIGURATION__TASK);
      if (_equals) {
        EObject container = ((TaskConfiguration)context).eContainer();
        if ((container instanceof AssembledWorkflow)) {
          CompositeWorkflow parentWorkflow = this.getParentWorkflow(((Workflow)container));
          if ((parentWorkflow instanceof CompositeWorkflow)) {
            return Scopes.scopeFor(parentWorkflow.getTasks());
          }
        }
      }
    }
    if ((context instanceof ExperimentTaskConfiguraiton)) {
      boolean _equals_1 = Objects.equals(reference, XDSLPackage.Literals.EXPERIMENT_TASK_CONFIGURAITON__TASK);
      if (_equals_1) {
        EObject container_1 = ((ExperimentTaskConfiguraiton)context).eContainer();
        if ((container_1 instanceof Space)) {
          CompositeWorkflow parentWorkflow_1 = this.getParentWorkflow(((Space)container_1).getAssembledWorkflow());
          if ((parentWorkflow_1 instanceof CompositeWorkflow)) {
            return Scopes.scopeFor(parentWorkflow_1.getTasks());
          }
        }
      }
    }
    return super.getScope(context, reference);
  }
}
