services:
  lang-server:
    build:
      context: ./editor/dsl/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/opt/logs/:wr
      - ./examples/:/workspaces/:wr
    ports:
      - "5007:5007"
    networks:
      - yamas

  vscode:
    build:
      context: ./editor/vscode/
      dockerfile: Dockerfile
    environment:
      - CODE_SERVER_HOST=0.0.0.0
      - CODE_SERVER_PORT=8080
      - CODE_SERVER_WELCOME_TEXT="WELCOME TO MSV IDE"
      - LANG_SERVER_HOST=lang-server
      - LANG_SERVER_PORT=5007
    volumes:
      - ./examples/:/workspaces/:wr
      - ./logs:/opt/logs/:wr
    ports:
      - "8001:8080"    
    depends_on:
      - lang-server
    networks:
      - yamas

  fs:
    build:
      context: ./storage/fs/
      dockerfile: Dockerfile
    volumes:
      - ./examples/:/workspaces/:wr
      - ./logs:/opt/logs/:wr
    ports:
      - "8005:5000"    
    depends_on:
      - vscode
    networks:
      - yamas

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - dal_data:/usr/share/elasticsearch/data
    networks:
      - yamas

  dal:
    build:
      context: ./dal/
      dockerfile: Dockerfile
    ports:
      - "8004:5000"
    depends_on:
      - elasticsearch
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./logs:/opt/logs/:wr
    networks:
      - yamas

  vis-api:
    build:
      context: ./visualizer/backend/
      dockerfile: Dockerfile
    ports:
      - "8003"
    volumes:
      - .env:/app/.env
      - .output:/app/output
    restart: unless-stopped
    networks:
      - yamas

  vis-front:
    build:
      context: ./visualizer/frontend/
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - vis-api
    networks:
      - yamas
    
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    expose:
      - '27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - yamas

  portal:
    build:
      context: ./portal/web-app/
      dockerfile: Dockerfile
    ports:
      - '8000:7001'
    networks:
      - yamas

volumes:
  dal_data:
  mongo_data:

networks:
  yamas:
    driver: bridge
    
