services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - dal_data:/usr/share/elasticsearch/data

  dal:
    build:
      context: /home/abdullah/repos/mesev/dal/
      dockerfile: /home/abdullah/repos/mesev/dal/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

volumes:
  dal_data:

