services:
  lang-server:
    build:
      context: ./editor/dsl/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/opt/logs/:wr
      - ./workspaces:/workspaces/:wr
    ports:
      - "5007:5007"
    networks:
      - yamas

  vscode:
    build:
      context: ./editor/vscode/
      dockerfile: Dockerfile
    environment:
      - CODE_SERVER_HOST=0.0.0.0
      - CODE_SERVER_PORT=8080
      - CODE_SERVER_WELCOME_TEXT="WELCOME TO MSV IDE"
      - LANG_SERVER_HOST=lang-server
      - LANG_SERVER_PORT=5007
    volumes:
      - ./workspaces/:/workspaces/:wr
      - ./logs:/opt/logs/:wr
    ports:
      - "8080:8080"    
    depends_on:
      - lang-server
    networks:
      - yamas

  fs:
    build:
      context: ./storage/fs/
      dockerfile: Dockerfile
    volumes:
      - ./workspaces/:/workspaces/:wr
      - ./logs:/opt/logs/:wr
    ports:
      - "8002:5000"    
    depends_on:
      - vscode
    networks:
      - yamas

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - dal_data:/usr/share/elasticsearch/data
    networks:
      - yamas

  dal:
    build:
      context: ./dal/
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    depends_on:
      - elasticsearch
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./logs:/opt/logs/:wr
    networks:
      - mseve

  vis-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    volumes:
      - .env:/app/.env
      - ${OUTPUT_DATA_PATH}:/app/output
    restart: unless-stopped

  vis-front:
    build:
      context: ./visualizer/frontend/
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    depends_on:
      - vis-api
    networks:
      - yamas
    
volumes:
  dal_data:

networks:
  yamas:
    driver: bridge
    
