services:
  lang-server:
    build:
      context: ./editor/dsl/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/opt/logs/:wr
      - ./workspace:/home/user/workspace/:wr
    ports:
      - "5007:5007"
    networks:
      - mseve

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - dal_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mseve

  dal:
    build:
      context: ./dal/
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    depends_on:
      - elasticsearch
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./logs:/opt/logs/:wr
      
    networks:
      - mseve

volumes:
  dal_data:

networks:
  mseve:
    driver: bridge
    
