/*
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.serializer;

import com.google.inject.Inject;
import com.mesev.dsl.services.XDSLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class XDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected XDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_PrimitiveType_BlobKeyword_1_3_or_BooleanKeyword_1_1_or_IntegerKeyword_1_0_or_StringKeyword_1_2;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (XDSLGrammarAccess) access;
		match_PrimitiveType_BlobKeyword_1_3_or_BooleanKeyword_1_1_or_IntegerKeyword_1_0_or_StringKeyword_1_2 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getPrimitiveTypeAccess().getBlobKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getPrimitiveTypeAccess().getBooleanKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getPrimitiveTypeAccess().getIntegerKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getPrimitiveTypeAccess().getStringKeyword_1_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_PrimitiveType_BlobKeyword_1_3_or_BooleanKeyword_1_1_or_IntegerKeyword_1_0_or_StringKeyword_1_2.equals(syntax))
				emit_PrimitiveType_BlobKeyword_1_3_or_BooleanKeyword_1_1_or_IntegerKeyword_1_0_or_StringKeyword_1_2(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'Integer' | 'Boolean' | 'String' | 'Blob'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_PrimitiveType_BlobKeyword_1_3_or_BooleanKeyword_1_1_or_IntegerKeyword_1_0_or_StringKeyword_1_2(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
