/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL.impl;

import com.mesev.dsl.xDSL.ComponentWithData;
import com.mesev.dsl.xDSL.XDSLPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component With Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComponentWithDataImpl extends MinimalEObjectImpl.Container implements ComponentWithData
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentWithDataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XDSLPackage.Literals.COMPONENT_WITH_DATA;
  }

} //ComponentWithDataImpl
