/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL.impl;

import com.mesev.dsl.xDSL.ExperimentTaskConfiguraitonBody;
import com.mesev.dsl.xDSL.Param;
import com.mesev.dsl.xDSL.XDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Experiment Task Configuraiton Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.impl.ExperimentTaskConfiguraitonBodyImpl#getParams <em>Params</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.impl.ExperimentTaskConfiguraitonBodyImpl#getNotImplemented <em>Not Implemented</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExperimentTaskConfiguraitonBodyImpl extends MinimalEObjectImpl.Container implements ExperimentTaskConfiguraitonBody
{
  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<Param> params;

  /**
   * The default value of the '{@link #getNotImplemented() <em>Not Implemented</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotImplemented()
   * @generated
   * @ordered
   */
  protected static final String NOT_IMPLEMENTED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNotImplemented() <em>Not Implemented</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotImplemented()
   * @generated
   * @ordered
   */
  protected String notImplemented = NOT_IMPLEMENTED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExperimentTaskConfiguraitonBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XDSLPackage.Literals.EXPERIMENT_TASK_CONFIGURAITON_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Param> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<Param>(Param.class, this, XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNotImplemented()
  {
    return notImplemented;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNotImplemented(String newNotImplemented)
  {
    String oldNotImplemented = notImplemented;
    notImplemented = newNotImplemented;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__NOT_IMPLEMENTED, oldNotImplemented, notImplemented));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS:
        return getParams();
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__NOT_IMPLEMENTED:
        return getNotImplemented();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends Param>)newValue);
        return;
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__NOT_IMPLEMENTED:
        setNotImplemented((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS:
        getParams().clear();
        return;
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__NOT_IMPLEMENTED:
        setNotImplemented(NOT_IMPLEMENTED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__PARAMS:
        return params != null && !params.isEmpty();
      case XDSLPackage.EXPERIMENT_TASK_CONFIGURAITON_BODY__NOT_IMPLEMENTED:
        return NOT_IMPLEMENTED_EDEFAULT == null ? notImplemented != null : !NOT_IMPLEMENTED_EDEFAULT.equals(notImplemented);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (notImplemented: ");
    result.append(notImplemented);
    result.append(')');
    return result.toString();
  }

} //ExperimentTaskConfiguraitonBodyImpl
