/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL.impl;

import com.mesev.dsl.xDSL.Metric;
import com.mesev.dsl.xDSL.Parameter;
import com.mesev.dsl.xDSL.TaskSpecification;
import com.mesev.dsl.xDSL.XDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Task Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.impl.TaskSpecificationImpl#getMetrics <em>Metrics</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.impl.TaskSpecificationImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.impl.TaskSpecificationImpl#getImplementation <em>Implementation</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.impl.TaskSpecificationImpl#getDependency <em>Dependency</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaskSpecificationImpl extends WorkflowImpl implements TaskSpecification
{
  /**
   * The cached value of the '{@link #getMetrics() <em>Metrics</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetrics()
   * @generated
   * @ordered
   */
  protected EList<Metric> metrics;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parameters;

  /**
   * The default value of the '{@link #getImplementation() <em>Implementation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImplementation()
   * @generated
   * @ordered
   */
  protected static final String IMPLEMENTATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImplementation() <em>Implementation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImplementation()
   * @generated
   * @ordered
   */
  protected String implementation = IMPLEMENTATION_EDEFAULT;

  /**
   * The default value of the '{@link #getDependency() <em>Dependency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency()
   * @generated
   * @ordered
   */
  protected static final String DEPENDENCY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependency() <em>Dependency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency()
   * @generated
   * @ordered
   */
  protected String dependency = DEPENDENCY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaskSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XDSLPackage.Literals.TASK_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Metric> getMetrics()
  {
    if (metrics == null)
    {
      metrics = new EObjectContainmentEList<Metric>(Metric.class, this, XDSLPackage.TASK_SPECIFICATION__METRICS);
    }
    return metrics;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getParameters()
  {
    if (parameters == null)
    {
      parameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, XDSLPackage.TASK_SPECIFICATION__PARAMETERS);
    }
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getImplementation()
  {
    return implementation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImplementation(String newImplementation)
  {
    String oldImplementation = implementation;
    implementation = newImplementation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDSLPackage.TASK_SPECIFICATION__IMPLEMENTATION, oldImplementation, implementation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDependency()
  {
    return dependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDependency(String newDependency)
  {
    String oldDependency = dependency;
    dependency = newDependency;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDSLPackage.TASK_SPECIFICATION__DEPENDENCY, oldDependency, dependency));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XDSLPackage.TASK_SPECIFICATION__METRICS:
        return ((InternalEList<?>)getMetrics()).basicRemove(otherEnd, msgs);
      case XDSLPackage.TASK_SPECIFICATION__PARAMETERS:
        return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XDSLPackage.TASK_SPECIFICATION__METRICS:
        return getMetrics();
      case XDSLPackage.TASK_SPECIFICATION__PARAMETERS:
        return getParameters();
      case XDSLPackage.TASK_SPECIFICATION__IMPLEMENTATION:
        return getImplementation();
      case XDSLPackage.TASK_SPECIFICATION__DEPENDENCY:
        return getDependency();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XDSLPackage.TASK_SPECIFICATION__METRICS:
        getMetrics().clear();
        getMetrics().addAll((Collection<? extends Metric>)newValue);
        return;
      case XDSLPackage.TASK_SPECIFICATION__PARAMETERS:
        getParameters().clear();
        getParameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case XDSLPackage.TASK_SPECIFICATION__IMPLEMENTATION:
        setImplementation((String)newValue);
        return;
      case XDSLPackage.TASK_SPECIFICATION__DEPENDENCY:
        setDependency((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XDSLPackage.TASK_SPECIFICATION__METRICS:
        getMetrics().clear();
        return;
      case XDSLPackage.TASK_SPECIFICATION__PARAMETERS:
        getParameters().clear();
        return;
      case XDSLPackage.TASK_SPECIFICATION__IMPLEMENTATION:
        setImplementation(IMPLEMENTATION_EDEFAULT);
        return;
      case XDSLPackage.TASK_SPECIFICATION__DEPENDENCY:
        setDependency(DEPENDENCY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XDSLPackage.TASK_SPECIFICATION__METRICS:
        return metrics != null && !metrics.isEmpty();
      case XDSLPackage.TASK_SPECIFICATION__PARAMETERS:
        return parameters != null && !parameters.isEmpty();
      case XDSLPackage.TASK_SPECIFICATION__IMPLEMENTATION:
        return IMPLEMENTATION_EDEFAULT == null ? implementation != null : !IMPLEMENTATION_EDEFAULT.equals(implementation);
      case XDSLPackage.TASK_SPECIFICATION__DEPENDENCY:
        return DEPENDENCY_EDEFAULT == null ? dependency != null : !DEPENDENCY_EDEFAULT.equals(dependency);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (implementation: ");
    result.append(implementation);
    result.append(", dependency: ");
    result.append(dependency);
    result.append(')');
    return result.toString();
  }

} //TaskSpecificationImpl
