/*
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.parser.antlr;

import com.google.inject.Inject;
import cz.smartarch.yamas.dsl.parser.antlr.internal.InternalXDSLParser;
import cz.smartarch.yamas.dsl.services.XDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XDSLParser extends AbstractAntlrParser {

	@Inject
	private XDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXDSLParser createParser(XtextTokenStream stream) {
		return new InternalXDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public XDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
