services:
  vis-api:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    volumes:
      - .env:/app/.env
      - .output:/app/output
    restart: unless-stopped
    networks:      
      - vis
  #  stdin_open: true   # same as -i
  #  tty: true          # same as -t

  vis-front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    networks:
      - vis
        #   stdin_open: true   # same as -i
        # tty: true          # same as -t

networks:
  vis:
    driver: bridge
    
