/*
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXDSLScopeProvider extends DelegatingScopeProvider {
}
