/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assembled Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.AssembledWorkflow#getParent <em>Parent</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.AssembledWorkflow#getSubstitutedTasks <em>Substituted Tasks</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getAssembledWorkflow()
 * @model
 * @generated
 */
public interface AssembledWorkflow extends Workflow
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(Workflow)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getAssembledWorkflow_Parent()
   * @model
   * @generated
   */
  Workflow getParent();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.AssembledWorkflow#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(Workflow value);

  /**
   * Returns the value of the '<em><b>Substituted Tasks</b></em>' containment reference list.
   * The list contents are of type {@link cz.smartarch.yamas.dsl.xDSL.SubstitutedTask}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substituted Tasks</em>' containment reference list.
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getAssembledWorkflow_SubstitutedTasks()
   * @model containment="true"
   * @generated
   */
  EList<SubstitutedTask> getSubstitutedTasks();

} // AssembledWorkflow
