/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Control#getFlows <em>Flows</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Control#getNotImplemented <em>Not Implemented</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getControl()
 * @model
 * @generated
 */
public interface Control extends EObject
{
  /**
   * Returns the value of the '<em><b>Flows</b></em>' containment reference list.
   * The list contents are of type {@link cz.smartarch.yamas.dsl.xDSL.ExperimentFlow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flows</em>' containment reference list.
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getControl_Flows()
   * @model containment="true"
   * @generated
   */
  EList<ExperimentFlow> getFlows();

  /**
   * Returns the value of the '<em><b>Not Implemented</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not Implemented</em>' attribute.
   * @see #setNotImplemented(String)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getControl_NotImplemented()
   * @model
   * @generated
   */
  String getNotImplemented();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Control#getNotImplemented <em>Not Implemented</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not Implemented</em>' attribute.
   * @see #getNotImplemented()
   * @generated
   */
  void setNotImplemented(String value);

} // Control
