/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getInputDataTask <em>Input Data Task</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#isAsInputTask <em>As Input Task</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getInputData <em>Input Data</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getOutputDataTask <em>Output Data Task</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#isAsOutputTask <em>As Output Task</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getOutputData <em>Output Data</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink()
 * @model
 * @generated
 */
public interface DataLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Input Data Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Data Task</em>' reference.
   * @see #setInputDataTask(Task)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_InputDataTask()
   * @model
   * @generated
   */
  Task getInputDataTask();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getInputDataTask <em>Input Data Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Data Task</em>' reference.
   * @see #getInputDataTask()
   * @generated
   */
  void setInputDataTask(Task value);

  /**
   * Returns the value of the '<em><b>As Input Task</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>As Input Task</em>' attribute.
   * @see #setAsInputTask(boolean)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_AsInputTask()
   * @model
   * @generated
   */
  boolean isAsInputTask();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#isAsInputTask <em>As Input Task</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>As Input Task</em>' attribute.
   * @see #isAsInputTask()
   * @generated
   */
  void setAsInputTask(boolean value);

  /**
   * Returns the value of the '<em><b>Input Data</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Data</em>' reference.
   * @see #setInputData(Data)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_InputData()
   * @model
   * @generated
   */
  Data getInputData();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getInputData <em>Input Data</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Data</em>' reference.
   * @see #getInputData()
   * @generated
   */
  void setInputData(Data value);

  /**
   * Returns the value of the '<em><b>Output Data Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Data Task</em>' reference.
   * @see #setOutputDataTask(Task)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_OutputDataTask()
   * @model
   * @generated
   */
  Task getOutputDataTask();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getOutputDataTask <em>Output Data Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Data Task</em>' reference.
   * @see #getOutputDataTask()
   * @generated
   */
  void setOutputDataTask(Task value);

  /**
   * Returns the value of the '<em><b>As Output Task</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>As Output Task</em>' attribute.
   * @see #setAsOutputTask(boolean)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_AsOutputTask()
   * @model
   * @generated
   */
  boolean isAsOutputTask();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#isAsOutputTask <em>As Output Task</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>As Output Task</em>' attribute.
   * @see #isAsOutputTask()
   * @generated
   */
  void setAsOutputTask(boolean value);

  /**
   * Returns the value of the '<em><b>Output Data</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Data</em>' reference.
   * @see #setOutputData(Data)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getDataLink_OutputData()
   * @model
   * @generated
   */
  Data getOutputData();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.DataLink#getOutputData <em>Output Data</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Data</em>' reference.
   * @see #getOutputData()
   * @generated
   */
  void setOutputData(Data value);

} // DataLink
