/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Experiment Step</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getExperimentStep()
 * @model
 * @generated
 */
public interface ExperimentStep extends EObject
{
} // ExperimentStep
