/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.NodeLink#getTask <em>Task</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.NodeLink#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getNodeLink()
 * @model
 * @generated
 */
public interface NodeLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' reference.
   * @see #setTask(Task)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getNodeLink_Task()
   * @model
   * @generated
   */
  Task getTask();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.NodeLink#getTask <em>Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task</em>' reference.
   * @see #getTask()
   * @generated
   */
  void setTask(Task value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getNodeLink_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.NodeLink#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

} // NodeLink
