/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parallel Nodes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.ParallelNodes#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParallelNodes()
 * @model
 * @generated
 */
public interface ParallelNodes extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodes</b></em>' reference list.
   * The list contents are of type {@link cz.smartarch.yamas.dsl.xDSL.ExperimentNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' reference list.
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParallelNodes_Nodes()
   * @model
   * @generated
   */
  EList<ExperimentNode> getNodes();

} // ParallelNodes
