/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getName <em>Name</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getType <em>Type</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getDefaultValueString <em>Default Value String</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getDefaultValueInt <em>Default Value Int</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getRangeValue <em>Range Value</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getEnumValue <em>Enum Value</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getValueConstraint <em>Value Constraint</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(ParameterType)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_Type()
   * @model containment="true"
   * @generated
   */
  ParameterType getType();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(ParameterType value);

  /**
   * Returns the value of the '<em><b>Default Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value String</em>' attribute.
   * @see #setDefaultValueString(String)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_DefaultValueString()
   * @model
   * @generated
   */
  String getDefaultValueString();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getDefaultValueString <em>Default Value String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value String</em>' attribute.
   * @see #getDefaultValueString()
   * @generated
   */
  void setDefaultValueString(String value);

  /**
   * Returns the value of the '<em><b>Default Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value Int</em>' attribute.
   * @see #setDefaultValueInt(int)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_DefaultValueInt()
   * @model
   * @generated
   */
  int getDefaultValueInt();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getDefaultValueInt <em>Default Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value Int</em>' attribute.
   * @see #getDefaultValueInt()
   * @generated
   */
  void setDefaultValueInt(int value);

  /**
   * Returns the value of the '<em><b>Range Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range Value</em>' containment reference.
   * @see #setRangeValue(ParamValueRange)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_RangeValue()
   * @model containment="true"
   * @generated
   */
  ParamValueRange getRangeValue();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getRangeValue <em>Range Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range Value</em>' containment reference.
   * @see #getRangeValue()
   * @generated
   */
  void setRangeValue(ParamValueRange value);

  /**
   * Returns the value of the '<em><b>Enum Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Value</em>' containment reference.
   * @see #setEnumValue(ParamValueEnum)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_EnumValue()
   * @model containment="true"
   * @generated
   */
  ParamValueEnum getEnumValue();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getEnumValue <em>Enum Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Value</em>' containment reference.
   * @see #getEnumValue()
   * @generated
   */
  void setEnumValue(ParamValueEnum value);

  /**
   * Returns the value of the '<em><b>Value Constraint</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Constraint</em>' attribute.
   * @see #setValueConstraint(String)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getParameter_ValueConstraint()
   * @model
   * @generated
   */
  String getValueConstraint();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.Parameter#getValueConstraint <em>Value Constraint</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Constraint</em>' attribute.
   * @see #getValueConstraint()
   * @generated
   */
  void setValueConstraint(String value);

} // Parameter
