/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regular Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.RegularLink#getInput <em>Input</em>}</li>
 *   <li>{@link cz.smartarch.yamas.dsl.xDSL.RegularLink#getOuput <em>Ouput</em>}</li>
 * </ul>
 *
 * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getRegularLink()
 * @model
 * @generated
 */
public interface RegularLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' containment reference.
   * @see #setInput(NodeLink)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getRegularLink_Input()
   * @model containment="true"
   * @generated
   */
  NodeLink getInput();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.RegularLink#getInput <em>Input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' containment reference.
   * @see #getInput()
   * @generated
   */
  void setInput(NodeLink value);

  /**
   * Returns the value of the '<em><b>Ouput</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ouput</em>' containment reference.
   * @see #setOuput(NodeLink)
   * @see cz.smartarch.yamas.dsl.xDSL.XDSLPackage#getRegularLink_Ouput()
   * @model containment="true"
   * @generated
   */
  NodeLink getOuput();

  /**
   * Sets the value of the '{@link cz.smartarch.yamas.dsl.xDSL.RegularLink#getOuput <em>Ouput</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ouput</em>' containment reference.
   * @see #getOuput()
   * @generated
   */
  void setOuput(NodeLink value);

} // RegularLink
