/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.Action#getActionName <em>Action Name</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.Action#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Action Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Name</em>' attribute.
   * @see #setActionName(String)
   * @see com.mesev.dsl.xDSL.XDSLPackage#getAction_ActionName()
   * @model
   * @generated
   */
  String getActionName();

  /**
   * Sets the value of the '{@link com.mesev.dsl.xDSL.Action#getActionName <em>Action Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Name</em>' attribute.
   * @see #getActionName()
   * @generated
   */
  void setActionName(String value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link com.mesev.dsl.xDSL.ActionArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see com.mesev.dsl.xDSL.XDSLPackage#getAction_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<ActionArgument> getArguments();

} // Action
