/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assembled Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.AssembledWorkflow#getParent <em>Parent</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.AssembledWorkflow#getTaskConfigurations <em>Task Configurations</em>}</li>
 * </ul>
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getAssembledWorkflow()
 * @model
 * @generated
 */
public interface AssembledWorkflow extends Workflow
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(Workflow)
   * @see com.mesev.dsl.xDSL.XDSLPackage#getAssembledWorkflow_Parent()
   * @model
   * @generated
   */
  Workflow getParent();

  /**
   * Sets the value of the '{@link com.mesev.dsl.xDSL.AssembledWorkflow#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(Workflow value);

  /**
   * Returns the value of the '<em><b>Task Configurations</b></em>' containment reference list.
   * The list contents are of type {@link com.mesev.dsl.xDSL.TaskConfiguration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task Configurations</em>' containment reference list.
   * @see com.mesev.dsl.xDSL.XDSLPackage#getAssembledWorkflow_TaskConfigurations()
   * @model containment="true"
   * @generated
   */
  EList<TaskConfiguration> getTaskConfigurations();

} // AssembledWorkflow
