/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component With Data</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getComponentWithData()
 * @model
 * @generated
 */
public interface ComponentWithData extends EObject
{
} // ComponentWithData
