/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.DataLink#getInputData <em>Input Data</em>}</li>
 *   <li>{@link com.mesev.dsl.xDSL.DataLink#getOutputData <em>Output Data</em>}</li>
 * </ul>
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getDataLink()
 * @model
 * @generated
 */
public interface DataLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Input Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Data</em>' attribute.
   * @see #setInputData(String)
   * @see com.mesev.dsl.xDSL.XDSLPackage#getDataLink_InputData()
   * @model
   * @generated
   */
  String getInputData();

  /**
   * Sets the value of the '{@link com.mesev.dsl.xDSL.DataLink#getInputData <em>Input Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Data</em>' attribute.
   * @see #getInputData()
   * @generated
   */
  void setInputData(String value);

  /**
   * Returns the value of the '<em><b>Output Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Data</em>' attribute.
   * @see #setOutputData(String)
   * @see com.mesev.dsl.xDSL.XDSLPackage#getDataLink_OutputData()
   * @model
   * @generated
   */
  String getOutputData();

  /**
   * Sets the value of the '{@link com.mesev.dsl.xDSL.DataLink#getOutputData <em>Output Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Data</em>' attribute.
   * @see #getOutputData()
   * @generated
   */
  void setOutputData(String value);

} // DataLink
