/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mesev.dsl.xDSL.Event#getEventValue <em>Event Value</em>}</li>
 * </ul>
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends Node
{
  /**
   * Returns the value of the '<em><b>Event Value</b></em>' attribute.
   * The literals are from the enumeration {@link com.mesev.dsl.xDSL.EventValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Value</em>' attribute.
   * @see com.mesev.dsl.xDSL.EventValue
   * @see #setEventValue(EventValue)
   * @see com.mesev.dsl.xDSL.XDSLPackage#getEvent_EventValue()
   * @model
   * @generated
   */
  EventValue getEventValue();

  /**
   * Sets the value of the '{@link com.mesev.dsl.xDSL.Event#getEventValue <em>Event Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Value</em>' attribute.
   * @see com.mesev.dsl.xDSL.EventValue
   * @see #getEventValue()
   * @generated
   */
  void setEventValue(EventValue value);

} // Event
