/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package com.mesev.dsl.xDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Data</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.mesev.dsl.xDSL.XDSLPackage#getOutputData()
 * @model
 * @generated
 */
public interface OutputData extends Data
{
} // OutputData
