/**
 * generated by Xtext 2.39.0-SNAPSHOT
 */
package cz.smartarch.yamas.dsl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XDSLStandaloneSetup extends XDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new XDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
